version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/siddhantprateek/qdrant"

[[transformers]]
name = "gofmt"