{
 "title": "Application Monitoring Copy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Grafana API response Status total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "grafana_api_response_status_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AlertManager HTTP request duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "alertmanager_http_request_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Cotainer Resource Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubelet Running Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "kubelet_running_pods", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grafana Alerting Discovered Configuration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "grafana_alerting_discovered_configurations",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus HTTP requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}