apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdapi
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qdapi
  template:
    metadata:
      labels:
        app: qdapi
    spec:
      containers:
      - name: qdapi
        image: siddhantprateek/qdapi
        ports:
        - containerPort: 80
        env:
        - name: QDRANT_ADDR
          value: qdrant-db:6334
        - name: PORT
          value: "80"
