apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdapi
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qdapi
  template:
    metadata:
      labels:
        app: qdapi
    spec:
      containers:
      - name: qdapi
        image: siddhantprateek/qdapi
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: qdapi-cfgmap

