apiVersion: v1
kind: Service
metadata:
  name: qdrant-db-service
  namespace: monitoring
spec:
  selector:
    app: qdrant-db
  ports:
    - name: web
      protocol: TCP
      port: 6333
      targetPort: 6333
    - name: grpc
      protocol: TCP
      port: 6334
      targetPort: 6334