apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-data-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  resources:
    request:
      storage: 10Gi