name: Qdrant Test - Go Test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: siddhantprateek/qdrant
      
      - name: Start Docker Compose services
        run: docker-compose -f docker-compose.yml up -d
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Run Go tests
        run: go test ./...

      - name: Clean up Docker Compose services
        run: docker-compose -f docker-compose.yml down