name: Qdrant Test - Go Test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: siddhantprateek/qdrant
      
      - name: Start Docker Compose services
        run: docker-compose -f docker-compose.yml up -d
      
      - name: Wait for services to start
        run: sleep 20s 
      
      - name: Check Qdrant App Server health
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:80)
          if [ $response -eq 200 ]; then
            echo "Qdrant App Server is Healthy."
          else
            echo "Qdrant App Server is not Healthy. Status code: $response"
            exit 1
          fi

      - name: Clean up Docker Compose services
        run: docker-compose -f docker-compose.yml down
