name: Kubeconform - Kubernetes manifests validation

on: push

jobs:
  kubeconform:
    
    runs-on: ubuntu-latest
    container: deck15/kubeval-tools:latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Kubernetes files into container
        run: |
          cp -r .kubernetes/* $GITHUB_WORKSPACE/.kubernetes/

      - name: Run Kubeconform
        run: |
          kubeconform -summary $GITHUB_WORKSPACE/.kubernetes/
